// Desc: This file contains the paths to the avatars that are used in the app.
export const avatars = [

    // Beginner avatars (EU flags)
    { path: '../assets/euflags/ad.png', display: require('../assets/euflags/ad.png'), level: 'Beginner' },
    { path: '../assets/euflags/al.png', display: require('../assets/euflags/al.png'), level: 'Beginner' },
    { path: '../assets/euflags/am.png', display: require('../assets/euflags/am.png'), level: 'Beginner' },
    { path: '../assets/euflags/at.png', display: require('../assets/euflags/at.png'), level: 'Beginner' },
    { path: '../assets/euflags/az.png', display: require('../assets/euflags/az.png'), level: 'Beginner' },
    { path: '../assets/euflags/ba.png', display: require('../assets/euflags/ba.png'), level: 'Beginner' },
    { path: '../assets/euflags/be.png', display: require('../assets/euflags/be.png'), level: 'Beginner' },
    { path: '../assets/euflags/bg.png', display: require('../assets/euflags/bg.png'), level: 'Beginner' },
    { path: '../assets/euflags/by.png', display: require('../assets/euflags/by.png'), level: 'Beginner' },
    { path: '../assets/euflags/ch.png', display: require('../assets/euflags/ch.png'), level: 'Beginner' },
    { path: '../assets/euflags/cy.png', display: require('../assets/euflags/cy.png'), level: 'Beginner' },
    { path: '../assets/euflags/cz.png', display: require('../assets/euflags/cz.png'), level: 'Beginner' },
    { path: '../assets/euflags/de.png', display: require('../assets/euflags/de.png'), level: 'Beginner' },
    { path: '../assets/euflags/dk.png', display: require('../assets/euflags/dk.png'), level: 'Beginner' },
    { path: '../assets/euflags/ee.png', display: require('../assets/euflags/ee.png'), level: 'Beginner' },
    { path: '../assets/euflags/es.png', display: require('../assets/euflags/es.png'), level: 'Beginner' },
    { path: '../assets/euflags/fi.png', display: require('../assets/euflags/fi.png'), level: 'Beginner' },
    { path: '../assets/euflags/fr.png', display: require('../assets/euflags/fr.png'), level: 'Beginner' },
    { path: '../assets/euflags/gb.png', display: require('../assets/euflags/gb.png'), level: 'Beginner' },
    { path: '../assets/euflags/ge.png', display: require('../assets/euflags/ge.png'), level: 'Beginner' },
    { path: '../assets/euflags/gr.png', display: require('../assets/euflags/gr.png'), level: 'Beginner' },
    { path: '../assets/euflags/hr.png', display: require('../assets/euflags/hr.png'), level: 'Beginner' },
    { path: '../assets/euflags/hu.png', display: require('../assets/euflags/hu.png'), level: 'Beginner' },
    { path: '../assets/euflags/ie.png', display: require('../assets/euflags/ie.png'), level: 'Beginner' },
    { path: '../assets/euflags/is.png', display: require('../assets/euflags/is.png'), level: 'Beginner' },
    { path: '../assets/euflags/it.png', display: require('../assets/euflags/it.png'), level: 'Beginner' },
    { path: '../assets/euflags/kz.png', display: require('../assets/euflags/kz.png'), level: 'Beginner' },
    { path: '../assets/euflags/li.png', display: require('../assets/euflags/li.png'), level: 'Beginner' },
    { path: '../assets/euflags/lt.png', display: require('../assets/euflags/lt.png'), level: 'Beginner' },
    { path: '../assets/euflags/lu.png', display: require('../assets/euflags/lu.png'), level: 'Beginner' },
    { path: '../assets/euflags/lv.png', display: require('../assets/euflags/lv.png'), level: 'Beginner' },
    { path: '../assets/euflags/mc.png', display: require('../assets/euflags/mc.png'), level: 'Beginner' },
    { path: '../assets/euflags/md.png', display: require('../assets/euflags/md.png'), level: 'Beginner' },
    { path: '../assets/euflags/me.png', display: require('../assets/euflags/me.png'), level: 'Beginner' },
    { path: '../assets/euflags/mk.png', display: require('../assets/euflags/mk.png'), level: 'Beginner' },
    { path: '../assets/euflags/mt.png', display: require('../assets/euflags/mt.png'), level: 'Beginner' },
    { path: '../assets/euflags/nl.png', display: require('../assets/euflags/nl.png'), level: 'Beginner' },
    { path: '../assets/euflags/no.png', display: require('../assets/euflags/no.png'), level: 'Beginner' },
    { path: '../assets/euflags/pl.png', display: require('../assets/euflags/pl.png'), level: 'Beginner' },
    { path: '../assets/euflags/pt.png', display: require('../assets/euflags/pt.png'), level: 'Beginner' },
    { path: '../assets/euflags/ro.png', display: require('../assets/euflags/ro.png'), level: 'Beginner' },
    { path: '../assets/euflags/rs.png', display: require('../assets/euflags/rs.png'), level: 'Beginner' },
    { path: '../assets/euflags/se.png', display: require('../assets/euflags/se.png'), level: 'Beginner' },
    { path: '../assets/euflags/si.png', display: require('../assets/euflags/si.png'), level: 'Beginner' },
    { path: '../assets/euflags/sk.png', display: require('../assets/euflags/sk.png'), level: 'Beginner' },
    { path: '../assets/euflags/sm.png', display: require('../assets/euflags/sm.png'), level: 'Beginner' },
    { path: '../assets/euflags/ua.png', display: require('../assets/euflags/ua.png'), level: 'Beginner' },
    { path: '../assets/euflags/va.png', display: require('../assets/euflags/va.png'), level: 'Beginner' },
    { path: '../assets/euflags/eu.png', display: require('../assets/euflags/eu.png'), level: 'Beginner' },
    { path: '..assets/noneuflags/ca.png', display: require('../assets/noneuflags/ca.png'), level: 'Beginner' },
    { path: '../assets/noneuflags/us.png', display: require('../assets/noneuflags/us.png'), level: 'Beginner' },


    // Basic avatars
    { path: '../assets/avatars/testAvatar.jpeg', display: require('../assets/avatars/testAvatar.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar2.jpeg', display: require('../assets/avatars/testAvatar2.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar3.jpeg', display: require('../assets/avatars/testAvatar3.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar4.jpeg', display: require('../assets/avatars/testAvatar4.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar5.jpeg', display: require('../assets/avatars/testAvatar5.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar6.jpeg', display: require('../assets/avatars/testAvatar6.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar7.jpeg', display: require('../assets/avatars/testAvatar7.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar8.jpeg', display: require('../assets/avatars/testAvatar8.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar9.jpeg', display: require('../assets/avatars/testAvatar9.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar10.jpeg', display: require('../assets/avatars/testAvatar10.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar11.jpeg', display: require('../assets/avatars/testAvatar11.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar12.jpeg', display: require('../assets/avatars/testAvatar12.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar13.jpeg', display: require('../assets/avatars/testAvatar13.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar14.jpeg', display: require('../assets/avatars/testAvatar14.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar15.jpeg', display: require('../assets/avatars/testAvatar15.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar16.jpeg', display: require('../assets/avatars/testAvatar16.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar17.jpeg', display: require('../assets/avatars/testAvatar17.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar18.jpeg', display: require('../assets/avatars/testAvatar18.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar19.jpeg', display: require('../assets/avatars/testAvatar19.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar20.jpeg', display: require('../assets/avatars/testAvatar20.jpeg'), level: 'Basic' },
    { path: '../assets/avatars/testAvatar21.jpeg', display: require('../assets/avatars/testAvatar21.jpeg'), level: 'Basic' },
];