// Desc: This file contains the paths to the avatars that are used in the app.
export const avatars = [
        { path: '../assets/avatars/testAvatar.jpeg', display: require('../assets/avatars/testAvatar.jpeg') },
        { path: '../assets/avatars/testAvatar2.jpeg', display: require('../assets/avatars/testAvatar2.jpeg') },
        { path: '../assets/avatars/testAvatar3.jpeg', display: require('../assets/avatars/testAvatar3.jpeg') },
        { path: '../assets/avatars/testAvatar4.jpeg', display: require('../assets/avatars/testAvatar4.jpeg') },
        { path: '../assets/avatars/testAvatar5.jpeg', display: require('../assets/avatars/testAvatar5.jpeg') },
        { path: '../assets/avatars/testAvatar6.jpeg', display: require('../assets/avatars/testAvatar6.jpeg') },
        { path: '../assets/avatars/testAvatar7.jpeg', display: require('../assets/avatars/testAvatar7.jpeg') },
        { path: '../assets/avatars/testAvatar8.jpeg', display: require('../assets/avatars/testAvatar8.jpeg') },
        { path: '../assets/avatars/testAvatar9.jpeg', display: require('../assets/avatars/testAvatar9.jpeg') },
        { path: '../assets/avatars/testAvatar10.jpeg', display: require('../assets/avatars/testAvatar10.jpeg') },
        { path: '../assets/avatars/testAvatar11.jpeg', display: require('../assets/avatars/testAvatar11.jpeg') },
        { path: '../assets/avatars/testAvatar12.jpeg', display: require('../assets/avatars/testAvatar12.jpeg') },
        { path: '../assets/avatars/testAvatar13.jpeg', display: require('../assets/avatars/testAvatar13.jpeg')},
        { path: '../assets/avatars/testAvatar14.jpeg', display: require('../assets/avatars/testAvatar14.jpeg') },
        { path: '../assets/avatars/testAvatar15.jpeg', display: require('../assets/avatars/testAvatar15.jpeg') },
        { path: '../assets/avatars/testAvatar16.jpeg', display: require('../assets/avatars/testAvatar16.jpeg') },
        { path: '../assets/avatars/testAvatar17.jpeg', display: require('../assets/avatars/testAvatar17.jpeg') },
        { path: '../assets/avatars/testAvatar18.jpeg', display: require('../assets/avatars/testAvatar18.jpeg') },
    ];