/**
 * AvatarPaths - Avatar image paths and definitions for the game.
 *
 * 
 * This file defines all avatar image paths and their properties for the game.
 * @author Sabata79
 * @since 2025-08-29
 */
// Avatar paths for the game

export const avatars = [

    // beginner avatars (EU flags)
    { path: '../../assets/euflags/at.webp', display: require('../../assets/euflags/at.webp'), level: 'beginner' },
    { path: '../../assets/euflags/be.webp', display: require('../../assets/euflags/be.webp'), level: 'beginner' },
    { path: '../../assets/euflags/cz.webp', display: require('../../assets/euflags/cz.webp'), level: 'beginner' },
    { path: '../../assets/euflags/de.webp', display: require('../../assets/euflags/de.webp'), level: 'beginner' },
    { path: '../../assets/euflags/dk.webp', display: require('../../assets/euflags/dk.webp'), level: 'beginner' },
    { path: '../../assets/euflags/ee.webp', display: require('../../assets/euflags/ee.webp'), level: 'beginner' },
    { path: '../../assets/euflags/es.webp', display: require('../../assets/euflags/es.webp'), level: 'beginner' },
    { path: '../../assets/euflags/fi.webp', display: require('../../assets/euflags/fi.webp'), level: 'beginner' },
    { path: '../../assets/euflags/fr.webp', display: require('../../assets/euflags/fr.webp'), level: 'beginner' },
    { path: '../../assets/euflags/gb.webp', display: require('../../assets/euflags/gb.webp'), level: 'beginner' },
    { path: '../../assets/euflags/gr.webp', display: require('../../assets/euflags/gr.webp'), level: 'beginner' },
    { path: '../../assets/euflags/hr.webp', display: require('../../assets/euflags/hr.webp'), level: 'beginner' },
    { path: '../../assets/euflags/ie.webp', display: require('../../assets/euflags/ie.webp'), level: 'beginner' },
    { path: '../../assets/euflags/is.webp', display: require('../../assets/euflags/is.webp'), level: 'beginner' },
    { path: '../../assets/euflags/it.webp', display: require('../../assets/euflags/it.webp'), level: 'beginner' },
    { path: '../../assets/euflags/lt.webp', display: require('../../assets/euflags/lt.webp'), level: 'beginner' },
    { path: '../../assets/euflags/lv.webp', display: require('../../assets/euflags/lv.webp'), level: 'beginner' },
    { path: '../../assets/euflags/no.webp', display: require('../../assets/euflags/no.webp'), level: 'beginner' },
    { path: '../../assets/euflags/pl.webp', display: require('../../assets/euflags/pl.webp'), level: 'beginner' },
    { path: '../../assets/euflags/pt.webp', display: require('../../assets/euflags/pt.webp'), level: 'beginner' },
    { path: '../../assets/euflags/se.webp', display: require('../../assets/euflags/se.webp'), level: 'beginner' },
    { path: '../../assets/euflags/nl.webp', display: require('../../assets/euflags/nl.webp'), level: 'beginner' },
    { path: '../../assets/euflags/eu.webp', display: require('../../assets/euflags/eu.webp'), level: 'beginner' },

    // non-EU flags
    { path: '../../assets/noneuflags/ca.webp', display: require('../../assets/noneuflags/ca.webp'), level: 'beginner' },
    { path: '../../assets/noneuflags/us.webp', display: require('../../assets/noneuflags/us.webp'), level: 'beginner' },



    // basic avatars
    { path: '../../assets/avatars/testAvatar.webp', display: require('../../assets/avatars/testAvatar.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar2.webp', display: require('../../assets/avatars/testAvatar2.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar3.webp', display: require('../../assets/avatars/testAvatar3.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar4.webp', display: require('../../assets/avatars/testAvatar4.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar5.webp', display: require('../../assets/avatars/testAvatar5.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar6.webp', display: require('../../assets/avatars/testAvatar6.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar7.webp', display: require('../../assets/avatars/testAvatar7.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar8.webp', display: require('../../assets/avatars/testAvatar8.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar9.webp', display: require('../../assets/avatars/testAvatar9.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar10.webp', display: require('../../assets/avatars/testAvatar10.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar11.webp', display: require('../../assets/avatars/testAvatar11.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar12.webp', display: require('../../assets/avatars/testAvatar12.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar13.webp', display: require('../../assets/avatars/testAvatar13.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar14.webp', display: require('../../assets/avatars/testAvatar14.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar15.webp', display: require('../../assets/avatars/testAvatar15.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar16.webp', display: require('../../assets/avatars/testAvatar16.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar17.webp', display: require('../../assets/avatars/testAvatar17.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar18.webp', display: require('../../assets/avatars/testAvatar18.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar19.webp', display: require('../../assets/avatars/testAvatar19.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar20.webp', display: require('../../assets/avatars/testAvatar20.webp'), level: 'basic' },
    { path: '../../assets/avatars/testAvatar21.webp', display: require('../../assets/avatars/testAvatar21.webp'), level: 'basic' },

    // advanced avatars
    { path: '../../assets/advancedAvatars/Advanced1.webp', display: require('../../assets/advancedAvatars/Advanced1.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced2.webp', display: require('../../assets/advancedAvatars/Advanced2.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced3.webp', display: require('../../assets/advancedAvatars/Advanced3.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced4.webp', display: require('../../assets/advancedAvatars/Advanced4.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced5.webp', display: require('../../assets/advancedAvatars/Advanced5.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced6.webp', display: require('../../assets/advancedAvatars/Advanced6.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced7.webp', display: require('../../assets/advancedAvatars/Advanced7.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced8.webp', display: require('../../assets/advancedAvatars/Advanced8.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced9.webp', display: require('../../assets/advancedAvatars/Advanced9.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced10.webp', display: require('../../assets/advancedAvatars/Advanced10.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced11.webp', display: require('../../assets/advancedAvatars/Advanced11.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced12.webp', display: require('../../assets/advancedAvatars/Advanced12.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced13.webp', display: require('../../assets/advancedAvatars/Advanced13.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced14.webp', display: require('../../assets/advancedAvatars/Advanced14.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced15.webp', display: require('../../assets/advancedAvatars/Advanced15.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced16.webp', display: require('../../assets/advancedAvatars/Advanced16.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced17.webp', display: require('../../assets/advancedAvatars/Advanced17.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced18.webp', display: require('../../assets/advancedAvatars/Advanced18.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced19.webp', display: require('../../assets/advancedAvatars/Advanced19.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced20.webp', display: require('../../assets/advancedAvatars/Advanced20.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced21.webp', display: require('../../assets/advancedAvatars/Advanced21.webp'), level: 'advanced' },
    { path: '../../assets/advancedAvatars/Advanced22.webp', display: require('../../assets/advancedAvatars/Advanced22.webp'), level: 'advanced' },

    // elite avatars
    { path: '../../assets/eliteAvatars/elite1.webp', display: require('../../assets/eliteAvatars/elite1.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite2.webp', display: require('../../assets/eliteAvatars/elite2.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite3.webp', display: require('../../assets/eliteAvatars/elite3.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite4.webp', display: require('../../assets/eliteAvatars/elite4.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite5.webp', display: require('../../assets/eliteAvatars/elite5.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite6.webp', display: require('../../assets/eliteAvatars/elite6.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite7.webp', display: require('../../assets/eliteAvatars/elite7.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite8.webp', display: require('../../assets/eliteAvatars/elite8.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite9.webp', display: require('../../assets/eliteAvatars/elite9.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite10.webp', display: require('../../assets/eliteAvatars/elite10.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite11.webp', display: require('../../assets/eliteAvatars/elite11.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite12.webp', display: require('../../assets/eliteAvatars/elite12.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite13.webp', display: require('../../assets/eliteAvatars/elite13.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite14.webp', display: require('../../assets/eliteAvatars/elite14.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite15.webp', display: require('../../assets/eliteAvatars/elite15.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite16.webp', display: require('../../assets/eliteAvatars/elite16.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite17.webp', display: require('../../assets/eliteAvatars/elite17.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite18.webp', display: require('../../assets/eliteAvatars/elite18.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite19.webp', display: require('../../assets/eliteAvatars/elite19.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite20.webp', display: require('../../assets/eliteAvatars/elite20.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite21.webp', display: require('../../assets/eliteAvatars/elite21.webp'), level: 'elite' },
    { path: '../../assets/eliteAvatars/elite22.webp', display: require('../../assets/eliteAvatars/elite22.webp'), level: 'elite' },

    // legendary avatars
    { path: '../../assets/legendaryAvatars/legendary1.webp', display: require('../../assets/legendaryAvatars/legendary1.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary2.webp', display: require('../../assets/legendaryAvatars/legendary2.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary3.webp', display: require('../../assets/legendaryAvatars/legendary3.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary4.webp', display: require('../../assets/legendaryAvatars/legendary4.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary5.webp', display: require('../../assets/legendaryAvatars/legendary5.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary6.webp', display: require('../../assets/legendaryAvatars/legendary6.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary7.webp', display: require('../../assets/legendaryAvatars/legendary7.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary8.webp', display: require('../../assets/legendaryAvatars/legendary8.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary9.webp', display: require('../../assets/legendaryAvatars/legendary9.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary10.webp', display: require('../../assets/legendaryAvatars/legendary10.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary11.webp', display: require('../../assets/legendaryAvatars/legendary11.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary12.webp', display: require('../../assets/legendaryAvatars/legendary12.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary13.webp', display: require('../../assets/legendaryAvatars/legendary13.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary14.webp', display: require('../../assets/legendaryAvatars/legendary14.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary15.webp', display: require('../../assets/legendaryAvatars/legendary15.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary16.webp', display: require('../../assets/legendaryAvatars/legendary16.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary17.webp', display: require('../../assets/legendaryAvatars/legendary17.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary18.webp', display: require('../../assets/legendaryAvatars/legendary18.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary19.webp', display: require('../../assets/legendaryAvatars/legendary19.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary20.webp', display: require('../../assets/legendaryAvatars/legendary20.webp'), level: 'legendary' },
    { path: '../../assets/legendaryAvatars/legendary21.webp', display: require('../../assets/legendaryAvatars/legendary21.webp'), level: 'legendary' },
];