// GameboardScreenStyles.js
// Styles for the Gameboard screen only
import { StyleSheet, Dimensions } from 'react-native';
import COLORS from '../constants/colors';
import SPACING from '../constants/spacing';
import TYPOGRAPHY from '../constants/typography';
const { width, height } = Dimensions.get('window');
const isSmallScreen = height < 650;
const isBigScreen = height >= 1050;

const styles = StyleSheet.create({
    gameboardContainer: {
        flex: 1,
        alignSelf: 'stretch',
    },
    gameboard: {
        flex: 1,
        marginTop: 90,
        alignItems: 'center',
        justifyContent: 'center',
        maxWidth: 500,
    },
    selectScore: {
        flex: 1,
        fontFamily: TYPOGRAPHY.fontFamily.bangers,
        alignItems: 'center',
        justifyContent: 'center',
        color: COLORS.overlayLight,
        width: 80,
        marginRight: SPACING.md,
        marginTop: SPACING.xs,
        fontSize: TYPOGRAPHY.fontSize.lg,
        textAlign: 'center',
        borderWidth: 1,
        borderColor: COLORS.white,
        borderRadius: 4,
        backgroundColor: COLORS.backgroundGray,
    },
    selectScorePressed: {
        flex: 1,
        fontFamily: TYPOGRAPHY.fontFamily.bangers,
        alignItems: 'center',
        justifyContent: 'center',
        color: COLORS.black,
        width: 80,
        marginRight: SPACING.md,
        marginTop: SPACING.xs,
        fontSize: TYPOGRAPHY.fontSize.lg,
        textAlign: 'center',
        borderWidth: 2,
        borderColor: 'red',
        borderRadius: 4,
        backgroundColor: COLORS.accentDark,
    },
    lockedField: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        color: COLORS.black,
        width: 80,
        marginRight: 15,
        marginTop: SPACING.xs,
        fontSize: TYPOGRAPHY.fontSize.lg,
        textAlign: 'center',
        borderWidth: 3,
        borderColor: 'green',
        borderRadius: 4,
        backgroundColor: COLORS.success,
    },
    item: {
        flex: 1,
        height: isSmallScreen ? 35 : isBigScreen ? 60 : 40,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 3,
        left: -10,
        ...COLORS.shadowStyle
    },
    icon: {
        justifyContent: 'center',
        alignItems: 'center',
        color: 'white',
    },
    sectionContainer: {
        width: 70,
        height: 70,
        marginTop: 50,
        marginLeft: 30,
        justifyContent: 'center',
        alignItems: 'center',
        padding: SPACING.sm,
        borderRadius: 100,
        borderWidth: 1,
        borderColor: 'white',
        backgroundColor: '#84786c',
        ...COLORS.shadowStyle
    },
    sectionContainerAchieved: {
        width: 72,
        height: 72,
        marginTop: 40,
        marginLeft: 10,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        borderRadius: 100,
        borderWidth: 3,
        borderColor: 'green',
        backgroundColor: '#3ea645b8',
        ...COLORS.whiteShadow
    },
    sectionBonusTxt: {
        fontSize: TYPOGRAPHY.fontSize.md,
        textAlign: 'center',
        color: '#222f3e',
        fontFamily: TYPOGRAPHY.fontFamily.bangers,
    },
    diceBorder: {
        width:'80%',
        height: isSmallScreen ? 50 : 60,
        borderWidth: 2,
        borderColor: '#ccc9c9',
        borderRadius: 4,
        alignItems: 'center',
        backgroundColor: '#000000',
        marginTop: -50,
    },
    inputIndexShown: {
        fontSize: TYPOGRAPHY.fontSize.lg,
        fontFamily: TYPOGRAPHY.fontFamily.bangers,
        color: '#333131ff',
        textAlign: 'center',
        textAlignVertical: 'center',
        lineHeight: TYPOGRAPHY.fontSize.lg,
    },
    gridTxt: {
        color: '#2c2418',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
        padding: SPACING.xs,
        marginTop: SPACING.xs,
        borderColor: COLORS.backgroundDark,
        borderRadius: 4,
        backgroundColor: COLORS.backgroundDark,
    },
    scoreText: {
        color: 'white',
        fontFamily: TYPOGRAPHY.fontFamily.bangers,
        fontSize: TYPOGRAPHY.fontSize.md,
        paddingRight: 5,
    },
    filterLayer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: COLORS.overlayDark,
        zIndex: 999,
        justifyContent: 'center',
        alignItems: 'center',
        display: 'flex',
        paddingBottom: "25%",
    },
    centeredText: {
        color: 'white',
        fontSize: TYPOGRAPHY.fontSize.lg,
        textAlign: 'center',
        textShadowColor: COLORS.error,
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 10,
        zIndex: 1000,
    },
});

export default styles;
