/**
 * playerCardStyles - Styles for the PlayerCard component, including modal, avatar, trophy, and score display.
 * Used to style player profile cards and related UI elements.
 *
 * @module styles/PlayerCardStyles
 * @author Sabata79
 * @since 2025-08-29
 */

import { StyleSheet } from 'react-native';
import { Dimensions } from 'react-native';
import COLORS from '../constants/colors';
import TYPOGRAPHY from '../constants/typography';
import SPACING from '../constants/spacing';

const { width, height } = Dimensions.get('window');
const isFoldScreen = width < 800;
const avatarSize = isFoldScreen ? 75 : 80;



const playerCardStyles = StyleSheet.create({
    playerCardMonthDark: {
        borderColor: '#F5F5F5',
    },

    // PlayerCard Styles
    playerCardContainer: {
        marginTop: 10,
        marginBottom: 10,
        alignItems: 'center',
    },
    playerInfoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        height: '20%',
        marginBottom: 5,
    },
    playerNameContainer: {
        textAlign: 'center',
    },
    playerCardName: {
        fontFamily: TYPOGRAPHY.fontFamily.montserratBold,
        fontSize: TYPOGRAPHY.fontSize.xl,
    },
    playerCardNameDark: {
        color: COLORS.textLight,
    },
    playerTextContainer: {
        alignItems: 'right',
        justifyContent: 'right',
        width: '65%',
        minHeight: 110,
        maxHeight: 110,
        marginBottom: 5,
        marginTop: 20,
        borderRadius: 3,
        backgroundColor: '#99949430',
    },
    playerTextContainerDark: {
        backgroundColor: '#574e4e55',
    },
    playerCardModalBackground: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        position: 'absolute',
        width: '100%',
        height: '100%',
    },
    playerCardModalContainer: {
        width: '80%',
        maxWidth: 350,
        marginTop: '5%',
        padding: 10,
        borderRadius: 10,
        alignItems: 'center',
        position: 'relative',
        overflow: 'visible',
    },
    playerCardModalContainerDark: {
        borderWidth: 1,
        borderColor: '#6d6161',
        borderRadius: 10,
    },
    avatarModalBackgroundImage: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: '108%',
        height: '105%',
        borderRadius: 10,
        opacity: 0.95,
        resizeMode: 'cover',
    },
    trophyContainer: {
        position: 'relative',
        justifyContent: 'center',
        alignItems: 'center',
        height: "100%",
        width: "100%",
    },
    playerCardTrophyImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    trophyText: {
        fontFamily: TYPOGRAPHY.fontFamily.montserratBold,
        position: 'absolute',
        bottom: -1,
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
        left: 0,
        right: 0,
        textAlign: 'center',
        color: COLORS.textDark,
        fontSize: TYPOGRAPHY.fontSize.xxxs,
        backgroundColor: COLORS.background,
    },
    // Avatar Styles
    avatarContainer: {
        width: 80,
        height: 80,
        borderRadius: 40,
        overflow: 'hidden',
        marginBottom: -60,
        padding: 1,
        borderColor: '#00000063',
        marginRight: 5,
        marginLeft: 5,
        marginTop: 10,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent',
    },
    avatarModalBackground: {
        flex: 1,
        marginTop: '15%',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    avatarModalContainer: {
        width: '80%',
        height: '90%',
        backgroundColor: '#141414',
        borderRadius: 10,
        padding: 10,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#fff',
    },
    avatarSelectionWrapper: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-around',
        width: '100%',
    },
    avatar: {
        width: "100%",
        height: "100%",
        borderRadius: 50,
        margin: 5,
        resizeMode: 'cover',
    },
    beginnerAvatar: {
        borderRadius: 0,
        width: 65,
        height: 45,
        resizeMode: 'cover',
        margin: 5,
        borderRadius: 3,
        borderWidth: 1,
        borderColor: '#4f4c4c36',
    },
    defaultAvatar: {
        borderRadius: 50,
        resizeMode: 'cover',
    },
    editAvatarButton: {
        position: 'absolute',
        bottom: 0,
        left: "65%",
        borderWidth: 1,
        backgroundColor: '#ff000096',
        borderRadius: 20,
        padding: 5,
    },
    avatarSelectText: {
        fontSize: 18,
        marginBottom: 20,
        textAlign: 'center',
        color: '#fff',
    },
    avatarModalImageContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
        marginBottom: 50,
        borderColor: '#fff',
        borderWidth: 2,
        flexWrap: 'wrap',
    },
    avatarModalImage: {
        width: avatarSize,
        height: avatarSize,
        borderRadius: avatarSize / 2,
        padding: 2,
        margin: 5,
        resizeMode: 'contain',
    },
    closeAvatarModalButton: {
        position: 'absolute',
        right: 10,
        top: 2,
        color: '#fff',
        fontSize: 22,
    },
    closeAvatarModalText: {
        color: '#fff',
        fontSize: 22,
        padding: 5,
    },
    scoreRow: {
        width: '100%',
        height: 15,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    playerCardScoresContainer: {
        marginTop: 4,
        marginBottom: 4,
        borderColor: 'black',
        borderRadius: 3,
        padding: 3,
        backgroundColor: '#00000027',
        width: '98%',
        flexDirection: 'column',
        justifyContent: 'space-between',
        height: 90,
    },
    evenRow: {
        backgroundColor: '#ffffff00',
    },
    evenRowDark: {
        backgroundColor: '#a9a6a658',
    },

    oddRow: {
        backgroundColor: '#00000010',
    },
    oddRowDark: {
        backgroundColor: '#4543438f',
    },
    playerCardScoresTitle: {
        fontFamily: TYPOGRAPHY.fontFamily.montserratBold,
        marginTop: 5,
        fontSize: TYPOGRAPHY.fontSize.sm,
        textAlign: 'center',
    },
    playerCardScoreItem: {
        fontFamily: TYPOGRAPHY.fontFamily.montserratMedium,
        fontSize: TYPOGRAPHY.fontSize.xxs,
        color: COLORS.textDark,
        width: '60%',
        marginLeft: 5,
        marginBottom: 2,

    },
    playerCardScoreDate: {
        fontFamily: TYPOGRAPHY.fontFamily.montserratMedium,
        fontSize: TYPOGRAPHY.fontSize.xxs,
        color: COLORS.textDark,
        textAlign: 'right',
        paddingTop: 2,
        marginRight: 5,
    },
    playerCardTrophyCase: {
        width: '98%',
        alignItems: 'center',
        opacity: 0.85,
    },
    playerCardTrophyCaseTitle: {
        fontFamily: TYPOGRAPHY.fontFamily.montserratBold,
        fontSize: TYPOGRAPHY.fontSize.sm,
        marginBottom: 2,
    },
    playerCardMonthsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        width: '100%',
    },
    playerCardMonth: {
        width: '23%',
        aspectRatio: 0.8,
        minHeight: 70,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 5,
        marginTop: 5,
        backgroundColor: COLORS.background,
        borderRadius: 5,
        position: 'relative',
        flexDirection: 'column',
        borderColor: COLORS.black,
        borderWidth: 1,
    },
    playerCardOngoingMonth: {
        borderColor: COLORS.success,
        borderWidth: 4,
        borderRadius: 5,
    },

    playerCardMonthText: {
        fontFamily: TYPOGRAPHY.fontFamily.montserratBold,
        fontSize: TYPOGRAPHY.fontSize.xxs,
        width: '100%',
        textAlign: 'center',
        color: COLORS.textDark,
        position: 'absolute',
        top: 0,
        marginBottom: 10,
        zIndex: 2,
        backgroundColor: COLORS.overlayLight,
        borderTopLeftRadius: 3,
        borderTopRightRadius: 3,
    },
    emptySlotText: {
        fontFamily: TYPOGRAPHY.fontFamily.montserratLight,
        fontSize: TYPOGRAPHY.fontSize.xxl,
        color: COLORS.textDark,
        textAlign: 'center',
    },
    rankSlotText: {
        fontFamily: TYPOGRAPHY.fontFamily.bangers,
        fontSize: TYPOGRAPHY.fontSize.xxl,
        color: COLORS.textDark,
        textAlign: 'center',
    },
    playerCardCloseButton: {
        position: 'absolute',
        right: 10,
        top: 0,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        margin: 10,
        zIndex: 3,
    },
    playerCardCloseText: {
        fontFamily: TYPOGRAPHY.fontFamily.bangers,
        color: COLORS.textDark,
        fontSize: TYPOGRAPHY.fontSize.xxl,
        top: -30,
        right: -15,
        zIndex: 10,
        padding: 15,
    },
    playerCardCloseTextDark: {
        color: COLORS.textLight,
    },
    nameAndLinkContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: 5,
    },
    linkIconContainerDark: {
        backgroundColor: COLORS.overlayLight,
    },
    playerStatsContainer: {
        marginTop: 2,
        alignItems: 'left',
        marginLeft: 5,
        borderRadius: 2,
        padding: 0,
    },
    playerStat: {
        fontFamily: TYPOGRAPHY.fontFamily.montserratExtraBold,
        fontSize: TYPOGRAPHY.fontSize.xxxs,
        color: COLORS.textDark,
        textAlign: 'center',
    },
    progressBar: {
        width: '85%',
        height: 15,
        marginLeft: 5,
        marginRight: 5,
        backgroundColor: '#F5F5F5',
        borderRadius: 2,
        marginVertical: 2,
        position: 'relative',
        borderWidth: 0.5,
        borderBottomWidth: 0,
        marginBottom: 2,
        alignSelf: 'center',
        textAlign: 'center',
        justifyContent: 'center',
    },
    progressFill: {
        height: '100%',
        backgroundColor: COLORS.success,
        borderRadius: 2,
    },
    progressPercentageText: {
        fontFamily: TYPOGRAPHY.fontFamily.montserratExtraBold,
        position: 'absolute',
        width: '100%',
        textAlign: 'center',
        color: COLORS.textDark,
        fontSize: TYPOGRAPHY.fontSize.xxs,
        lineHeight: TYPOGRAPHY.fontSize.xxs,
        padding: 1,
    },
    playerCardHeader: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingTop: 5,
        marginBottom: 5,
        zIndex: 10,
    },
    playerCardInfoWrapper: {
        width: '100%',
        paddingHorizontal: 5,
        marginBottom: 10,
    },
    playerCardTopScoresWrapper: {
        width: '100%',
        paddingHorizontal: 5,
        marginTop: 0,
        marginBottom: 0,
    },
    playerCardHeaderCentered: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        position: 'relative',
        marginTop: 5,
    },
    playerCardTextDark: {
        color: COLORS.textLight,
    },
    playerCardCloseButton: {
        position: 'absolute',
        right: 10,
        top: -5,
        backgroundColor: 'transparent',
        zIndex: 2,
    },
    // image-based ribbon
    ribbonImageWrapper: {
        position: 'absolute',
        top: -8,
        left: -8,
        width: 180,
        height: 180,
        zIndex: 20,
        overflow: 'visible',
    },
    ribbonLinkedImageWrapper: {
        position: 'absolute',
        top: -6,
        left: -6,
        width: 85,
        height: 85,
        zIndex: 20,
        overflow: 'visible',
    },
    ribbonImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'contain',
    },
    ribbonLabel: {
        position: 'absolute',
        left: -40,
        top: 40,
        right: 8,
        textAlign: 'center',
        fontFamily: TYPOGRAPHY.fontFamily.bangers,
        color: '#111',
        fontSize: TYPOGRAPHY.fontSize.md,
        zIndex: 30,
        transform: [{ rotate: '-45deg' }],
    },
    ribbonIcon: {
        postion: 'absolute',
        top: 15,
        left: -15,
        marginRight: 4,
    },
    ribbonLinkedLabel: {
        position: 'absolute',
        top: 10,
        left: 0,
        textAlign: 'center',
        fontFamily: TYPOGRAPHY.fontFamily.bangers,
        color: 'white',
        fontSize: TYPOGRAPHY.fontSize.xs,
        zIndex: 30,
        marginLeft: 2,
    },
});
export default playerCardStyles;