/**
 * styles - Main global styles for the application, including containers, backgrounds, overlays, and UI elements.
 * Used throughout the app for layout and visual consistency.
 * JSDoc comments and inline code comments must always be in English.
 * @module styles/styles
 */
import { Dimensions, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');
const isSmallScreen = height < 650;
const isBigScreen = height >= 1050;

export default styles = StyleSheet.create({

    container: {
        flex: 1,
        alignSelf: 'stretch',
    },
    background: {
        flex: 1,
        justifyContent: 'flex-start',
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    safeAreaView: {
        flex: 1,
    },
    overlay: {
        flex: 1,
        width: '100%',
        backgroundColor: 'rgba(0, 0, 0, 0.537)',
        maxWidth: 420,
        alignSelf: 'center',
    },
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
    },
    userContainer: {
        flex: 1,
        right: 10,
    },
    input: {
        padding: 10,
        width: "50%",
        maxWidth: 250,
        justifyContent: 'center',
        textAlign: 'center',
        fontFamily: 'AntonRegular',
        color: 'white',
        backgroundColor: '#6c6b6b',
        borderRadius: 5,
    },
    inputIndexShown: {
        fontSize: isSmallScreen ? 16 : isBigScreen ? 20 : 18,
        fontFamily: 'AntonRegular',
        color: '#333131ff', // Tekstin väri
        textAlign: 'center',
        textShadowColor: '#b09e9e',
        textShadowOffset: { width: 0.2, height: 0.2 },
        textShadowRadius: 1,
    },
    welcomeText: {
        fontSize: 18,
        top: -25,
        width: '90%',
        color: 'white',
        textAlign: 'center',
        fontFamily: 'AntonRegular',
        alignSelf: 'center',
        zIndex: 10,
    },
    linkContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#6c6b6b',
        marginTop: 10,
    },
    linkText: {
        fontSize: 14,
        width: '90%',
        color: '#ccc9c9',
        textAlign: 'center',
        fontFamily: 'AntonRegular',
        alignSelf: 'center',
        backgroundColor: '#6c6b6b',
        padding: 10,
    },
    linkNameContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
        backgroundColor: '#6c6b6b',
        width: "50%",
        borderRadius: 5,
    },
    pwInputWrapper: {
        marginTop: 10,
        alignItems: 'center',
        backgroundColor: '#6c6b6b',
        width: "50%",
        borderRadius: 5,
    },
    pwInput: {
        padding: 10,
        fontSize: 16,
        maxWidth: 200,
        justifyContent: 'center',
        textAlign: 'center',
        fontFamily: 'AntonRegular',
        color: 'white',
    },
    item: {
        flex: 1,
        height: isSmallScreen ? 35 : isBigScreen ? 60 : 40,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 3,
        left: -10,
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 10,
    },
    firstRowItem: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        maxWidth: 550,
        zIndex: 10,
    },

    firstRowCategoryText: {
        fontFamily: 'AntonRegular',
        fontSize: 16,
        color: '#ffffff',
        marginVertical: 0,
    },
    firstRow: {
        marginTop: isBigScreen ? '30%' : 0,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 0,
        margin: 0,
        zIndex: 10,
    },
    lastRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 5,
    },
    playerText: {
        fontWeight: 'bold',
        fontSize: 18,
        paddingTop: 5,
        textAlign: 'center',
    },
    diceContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    rowButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginBottom: 10,
    },
    fullWidthButton: {
        marginTop: 5,
        flexDirection: 'row',
        paddingLeft: 10,
        paddingRight: 10,
        backgroundColor: '#ee8d1ef5',
        borderWidth: 3,
        borderColor: 'orange',
        width: '96%',
        height: '10%',
        borderRadius: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 10,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },

    button: {
        margin: 5,
        marginTop: isSmallScreen ? 8 : 15,
        flexDirection: 'row',
        paddingLeft: 10,
        paddingRight: 10,
        backgroundColor: '#eeac1ef5',
        borderWidth: 3,
        borderColor: 'orange',
        width: isSmallScreen ? '32%' : isBigScreen ? '45%' : '39%',  // Suuremmat napit suuremmilla näytöillä
        height: isSmallScreen ? 41 : isBigScreen ? 60 : 50,
        borderRadius: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 10,
    },

    buttonPressed: {
        margin: 5,
        marginTop: 15,
        flexDirection: 'row',
        paddingLeft: 10,
        paddingRight: 10,
        backgroundColor:'#c28d1af5',
        borderWidth: 3,
        borderColor: '#ff4500',
        width: isSmallScreen ? '32%' : isBigScreen ? '45%' : '39%',
        height: isSmallScreen ? 41 : isBigScreen ? 60 : 50,
        borderRadius: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 0.0,
        shadowRadius: 0,
        elevation: 0,
        transform: [{ scale: 0.95 }],
    },
    userButton: {
        margin: 5,
        flexDirection: 'row',
        paddingLeft: 10,
        paddingRight: 10,
        backgroundColor: '#ee8d1ef5',
        borderWidth: 3,
        borderColor: 'black',
        width: '40%',
        height: '100%',
        borderRadius: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 10,
    },
    userButtonPressed: {
        margin: 5,
        flexDirection: 'row',
        paddingLeft: 10,
        paddingRight: 10,
        backgroundColor: 'orange',
        width: '40%',
        height: '100%',
        borderRadius: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 0.0,
        shadowRadius: 0,
        elevation: 0,
    },
    buttonText: {
        color: 'black',
        fontSize: 18,
        textAlign: 'center',
        fontFamily: 'AntonRegular',
    },
    nbrThrowsTextContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    nbrThrowsText: {
        fontSize: 17,
        fontFamily: 'Roboto',
        width: 30,
        height: 30,
        borderRadius: 60,
        borderWidth: 2,
        textAlign: 'center',
        alignContent: 'center',
        justifyContent: 'center',
        backgroundColor: '#fb0202ad',
    },
    lastItem: {
        flex: 6,
    },
    loadingContainer: {
        marginTop: 30,
    },
    icon: {
        justifyContent: 'center',
        alignItems: 'center',
        color: 'white',
    },
    gridTxt: {
        color: '#2c2418',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
        padding: 5,
        marginTop: 5,
        borderColor: '#ccc9c9',
        borderRadius: 4,
        backgroundColor: '#ccc9c9',
    },
    selectScore: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        color: 'grey',
        width: 80,
        marginRight: 15,
        marginTop: 5,
        fontSize: 20,
        textAlign: 'center',
        borderWidth: 1,
        borderColor: 'white',
        borderRadius: 4,
        backgroundColor: '#776c62',
    },
    selectScorePressed: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        color: 'black',
        width: 80,
        marginRight: 15,
        marginTop: 5,
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        borderWidth: 2,
        borderColor: 'red',
        borderRadius: 4,
        backgroundColor: '#cf6d52b8',
    },
    scoreText: {
        color: 'white',
        fontFamily: 'AntonRegular',
        paddingRight: 10,
    },
    lockedField: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        color: 'black',
        width: 80,
        marginRight: 15,
        marginTop: 5,
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        borderWidth: 3,
        borderColor: 'green',
        borderRadius: 4,
        backgroundColor: '#3ea645b8',
    },
    sectionContainer: {
        width: 70,
        height: 70,
        marginTop: 50,
        marginLeft: 30,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        borderRadius: 100,
        borderWidth: 1,
        borderColor: 'white',
        backgroundColor: '#84786c',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 10,
    },
    sectionContainerAchieved: {
        width: 72,
        height: 72,
        marginTop: 40,
        marginLeft: 10,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        borderRadius: 100,
        borderWidth: 3,
        borderColor: 'green',
        backgroundColor: '#3ea645b8',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    sectionBonusTxt: {
        fontSize: 12,
        textAlign: 'center',
        color: '#2c2418',
        fontFamily: 'AntonRegular',
    },
    gameboard: {
        flex: 1,
        marginTop: 90,
        alignItems: 'center',
        justifyContent: 'center',
        maxWidth: 500,
    },
    filterLayer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        zIndex: 999,
        justifyContent: 'center',
        alignItems: 'center',
        display: 'flex',
        paddingBottom: 150,
    },
    centeredText: {
        color: 'white',
        fontSize: isBigScreen ? 32 : 20,
        fontWeight: 'bold',
        textAlign: 'center',
        textShadowColor: '#ff0000',
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 10,
        zIndex: 1000,
    },
    diceBorder: {
        width: isSmallScreen ? '75%' : '80%',
        height: isSmallScreen ? 50 : 60,
        borderWidth: 2,
        borderColor: '#ccc9c9',
        borderRadius: 4,
        alignItems: 'center',
        backgroundColor: 'black',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 10,
        marginTop: -100,
    },
    row: {
        marginTop: 20,
        padding: 10,
    },
    flex: {
        flexDirection: 'row',
        justifyContent: 'center',
    },
    rulesContainer: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
    },
    rulesContent: {
        justifyContent: 'center',
        alignItems: 'center',
        padding: 15,
        backgroundColor: '#282828',
        borderRadius: 10,
    },
    rulesText: {
        fontSize: 16,
        top: -60,
        width: '90%',
        color: '#ccc9c9',
        textAlign: 'center',
        fontFamily: 'AntonRegular',
        alignSelf: 'center',
    },
    rulesAuxillaryText: {
        fontSize: 11,
        top: -50,
        marginLeft: 50,
        marginRight: 50,
        color: '#e1dfdf',
        textAlign: 'center',
        fontFamily: 'AntonRegular',
    },
    rulesCombination: {
        marginLeft: 20,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
        marginTop: 15,
    },
    rulesCombinationTxt: {
        flex: 1,
        fontSize: 12,
        color: '#ccc9c9',
        textAlign: 'center',
        justifyContent: 'center',
        marginBottom: 10,
        marginLeft: 10,
        marginRight: 10,
        fontFamily: 'AntonRegular',
    },
    smallText: {
        fontSize: 10,
        marginLeft: 10,
        color: 'white',
        width: 60,
    },
    lockedTextColor: {
        color: 'black',
    },
    scoreboardContainer: {
        alignSelf: 'center',
        borderRadius: 5,
        backgroundColor: 'rgba(0, 0, 0, 0.546)',
        width: '95%',
        textAlign: 'center',
        justifyContent: 'center',
        borderColor: '#393838',
        opacity: 0.96,
        borderWidth: 2,
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 5,
        },
        shadowOpacity: 0.5,
        shadowRadius: 3.84,
        elevation: 10,
    },
    cell: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        height: isSmallScreen ? 65 : 65,
        padding: 0,
        margin: 0,
    },

    medalCell: {
        justifyContent: 'center',
        height: 60,
        position: 'relative',
    },

    imageWrapper: {
        justifyContent: 'flex-start',
        alignItems: 'center',
        height: '100%',
        width: '100%',
    },

    scoreboardText: {
        fontSize: 14,
        textAlign: 'center',
        fontFamily: 'Roboto',
        fontWeight: '800',
        color: '#ffffff',
        paddingVertical: 5,
        lineHeight: 60,
    },
    scoreboardHeader: {
        fontSize: 14,
        textAlign: 'center',
        fontFamily: 'AntonRegular',
        color: '#f5f5f5',
        paddingVertical: 5,
    },

    //Modal
    modalCenteredView: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        maxHeight: '60%',
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 1,
    },
    modalView: {
        margin: 20,
        backgroundColor: '#ffffff',
        borderRadius: 5,
        padding: 30,
        alignItems: 'center',
        opacity: 0.95,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 8,
    },
    modalText: {
        marginBottom: 10,
        textAlign: 'center',
        fontSize: 16,
        color: 'black',
        fontWeight: '500',
    },
    modalButton: {
        borderRadius: 5,
        paddingVertical: 8,
        paddingHorizontal: 15,
        elevation: 3,
        backgroundColor: '#ffa500',
    },
    modalButtonText: {
        color: 'black',
        fontWeight: '600',
        textAlign: 'center',
        fontSize: 16,
    },
    modalCloseButton: {
        position: 'absolute',
        right: 20,
        top: 10,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
    },
    modalCloseButtonText: {
        color: 'black',
        fontSize: 22,
        fontWeight: 'bold',
    },
    modalItemRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 15,
        paddingVertical: 5,
        width: '100%',
    },
    modalSubText: {
        fontSize: 14,
        color: 'gray',
        textAlign: 'right',
        marginLeft: 10,
    },
    modalDivider: {
        height: 1,
        backgroundColor: '#d3d3d3',
        marginVertical: 5,
        width: '100%',
    },
    modalItemContainer: {
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 15,
    },
    modalSubText: {
        fontSize: 14,
        color: '#a9a9a9',
        textAlign: 'center',
        fontStyle: 'italic',
    },
    timer: {
        fontSize: 18,
        fontWeight: 'bold',
        color: 'black',
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: [{ translateX: -50 }, { translateY: -50 }],
    },
    // StartGame button
    startModalButton: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(1, 1, 1, 1)',
        maxHeight: '100%',
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 999,

    },
    // StartGame button text
    startModalButtonText: {
        color: 'white',
        textAlign: 'center',
        fontSize: 25,
        fontWeight: 'bold',
        textShadowColor: '#ff0000',
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 10,
        zIndex: 999,
    },
    tabContainer: {
        flexDirection: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        width: '100%',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        padding: 5,
        marginTop: 0, 
    },
    tabText: {
        flex: 1,
        fontSize: 14,
        lineHeight: 20,
        color: 'white',
        padding: 0,
        textAlign: 'center',
        margin: 5,
    },
    activeTab: {
        flex: 1,
        borderBottomWidth: 2,
        borderBottomColor: 'gold',

    },
    inactiveTab: {
        flex: 1,
    },
    scoresHeaderContainer: {
        alignItems: 'center',
        marginTop: 10,
    },
    scoresHeaderText: {
        fontSize: isSmallScreen ? 22 : 24,
        fontWeight: 'bold',
        color: '#f5f5f5',
    },
    registerImage: {
        width: width * 0.9,
        height: height * 0.4,
        maxWidth: 400,
        maxHeight: 400,
        marginBottom: -30,
    },
    hiThereImage: {
        width: width * 1,
        height: height * 0.5,
        maxWidth: 400,
        maxHeight: 400,
        marginBottom: -120,
        marginTop: -50,
    },
    defaultAvatarIcon: {
        height: 40,
        width: 40,
        borderRadius: 20,
        marginRight: 10,
        backgroundColor: 'black',
        justifyContent: 'center',
        alignItems: 'center',
        display: 'flex',
    },
    rankHeaderCell: {
        flex: 1.2,
        alignItems: 'center',
        justifyContent: 'center',
    },
    playerHeaderCell: {
        flex: 3,
        alignItems: 'center',
        justifyContent: 'center',
    },
    durationHeaderCell: {
        flex: 2,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 15,
    },
    pointsHeaderCell: {
        flex: 1.5,
        alignItems: 'center',
        justifyContent: 'center',
    },
    rankCell: {
        flex: 1.2,
        alignItems: 'center',
        justifyContent: 'center',
    },
    medal: {
        width: isSmallScreen ? 38 : 42,
        height: isSmallScreen ? 38 : 42,
        marginLeft: 0,
        alignSelf: 'center',
    },
    medalWrapper: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    rankText: {
        fontSize: 16,
        color: '#f5f5f5',
        textAlign: 'center',
    },
    playerCell: {
        flex: 3,
        justifyContent: 'flex-start',
    },
    playerWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    avatar: {
        width: isSmallScreen ? 30 : 40,
        height: isSmallScreen ? 30 : 40,
        borderRadius: isSmallScreen ? 15 : 20,
        marginRight: 10,
        marginLeft: 15,
        borderWidth: 1,
        borderColor: 'black',
    },
    beginnerAvatar: {
        borderRadius: 0,
        width: 35,
        height: 25,
        resizeMode: 'cover',
        marginLeft: 18,
        marginRight: 12,
        borderRadius: 2,
        borderWidth: 1,
        borderColor: '#4f4c4c36',
    },
    advancedAvatar: {
        borderRadius: 0,
        width: 40,
        height: 30,
        resizeMode: 'cover',
        marginLeft: 18,
        marginRight: 12,
    },
    defaultAvatarIcon: {
        width: isSmallScreen ? 30 : 40,
        height: isSmallScreen ? 30 : 40,
        borderRadius: isSmallScreen ? 15 : 20,
        backgroundColor: 'black',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
        marginLeft: 15,
    },
    playerNameText: {
        fontSize: 16,
        color: '#f5f5f5',
        marginLeft: 5,
        letterSpacing: -0.8,
    },

    durationCell: {
        flex: 2,
        alignItems: 'center',
        justifyContent: 'center',
    },
    durationText: {
        fontSize: 16,
        color: '#f5f5f5',
        textAlign: 'center',
        marginLeft: 15,
    },

    pointsCell: {
        flex: 1.5,
        alignItems: 'center',
        justifyContent: 'center',
    },
    pointsText: {
        fontSize: 16,
        color: '#f5f5f5',
        textAlign: 'center',
    },

});
