import { StyleSheet } from 'react-native';

const homeStyles = StyleSheet.create({
  homeContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    color: 'black',
  },
  rulesContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#282828',
    borderRadius: 10,
  },
  rowButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 10,
  },
  fullWidthButton: {
    marginTop: 5,
    flexDirection: 'row',
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: '#ee8d1ef5',
    borderWidth: 3,
    borderColor: 'orange',
    width: '96%',
    height: 50,
    borderRadius: 5,
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 10,
  },
  input: {
    padding: 8,
    margin: 10,
    width: 200,
    justifyContent: 'center',
    textAlign: 'center',
    fontFamily: 'AntonRegular',
    color: '#ccc9c9',
  },
  buttonText: {
    color: 'black',
    fontSize: 18,
    textAlign: 'center',
    fontFamily: 'AntonRegular',
  },
  button: {
    margin: 5,
    marginTop: 15,
    flexDirection: 'row',
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: '#ee8d1ef5',
    borderWidth: 3,
    borderColor: 'orange',
    width: '39%',
    height: 50,
    borderRadius: 5,
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 10,
  },
  homeButtonPressed: {
    margin: 15,
    flexDirection: 'row',
    padding: 5,
    backgroundColor: 'orange',
    width: 200,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  loadingContainer: {
    marginTop: 20,
  },
});

export default homeStyles;
