import { StyleSheet } from 'react-native';
import { Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');
const isFoldScreen = width < 800;
const avatarSize = isFoldScreen ? 75 : 80;


export default styles = StyleSheet.create({

    // PlayerCard Styles
    playerCardContainer: {
        marginTop: 10,
        marginBottom: 10,
        alignItems: 'center',
    },
    playerInfoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        height: '20%',
        marginBottom: 5,
    },
    playerNameContainer: {
        marginLeft: 5,
    },
    playerCardName: {
        marginTop: 5,
        fontSize: 24,
        fontWeight: 'bold',
    },
    playerTextContainer: {
        alignItems: 'right',
        justifyContent: 'right',
        width: '65%',
        minHeight: 110,
        maxHeight: 110,
        marginBottom: 5,
        marginTop: 20,
        borderRadius: 3,
        backgroundColor: '#00000030',
    },
    playerCardModalBackground: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        position: 'absolute',
        width: '100%',
        height: '100%',
    },
    playerCardModalContainer: {
        width: '80%',
        maxWidth: 350,
        marginTop: '5%',
        padding: 10,
        borderRadius: 10,
        alignItems: 'center',
        position: 'relative',
        overflow: 'hidden',
    },
    avatarModalBackgroundImage: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: '108%',
        height: '105%',
        borderRadius: 10,
        opacity: 0.95,
        resizeMode: 'cover',
    },
    trophyContainer: {
        position: 'relative',
        justifyContent: 'center',
        alignItems: 'center',
        height: "100%",
        width: "100%",
    },
    playerCardTrophyImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    trophyText: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        textAlign: 'center',
        color: 'black',
        fontSize: 9,
        fontWeight: 'bold',
        backgroundColor: '#f3f3f3',
    },
    // Avatar Styles
    avatarContainer: {
        width: 80,
        height: 80,
        borderRadius: 40,
        overflow: 'hidden',
        marginBottom: 0,
        padding: 1,
        borderColor: '#00000063',
        marginRight: 5,
        marginLeft: 5,
        marginTop: 10,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ffffff00',
    },
    avatarModalBackground: {
        flex: 1,
        marginTop: '15%',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    avatarModalContainer: {
        width: '80%',
        height: '90%',
        backgroundColor: '#141414',
        borderRadius: 10,
        padding: 10,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#fff',
    },
    avatarSelectionWrapper: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-around',
        width: '100%',
    },
    avatar: {
        width: "100%",
        height: "100%",
        borderRadius: 50,
        margin: 5,
        resizeMode: 'cover',
    },
    beginnerAvatar: {
        borderRadius: 0,
        width: 65,
        height: 45,
        resizeMode: 'cover',
        margin: 5,
        borderRadius: 3,
        borderWidth: 1,
        borderColor: '#4f4c4c36',
    },
    defaultAvatar: {
        borderRadius: 50,
        resizeMode: 'cover',
    },
    editAvatarButton: {
        position: 'absolute',
        bottom: 0,
        left: "65%",
        borderWidth: 1,
        backgroundColor: '#ff000096',
        borderRadius: 20,
        padding: 5,
    },
    avatarSelectText: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 20,
        textAlign: 'center',
        color: '#fff',
    },
    avatarModalImageContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
        marginBottom: 50,
        borderColor: '#fff',
        borderWidth: 2,
        flexWrap: 'wrap',
    },
    avatarModalImage: {
        width: avatarSize,
        height: avatarSize,
        borderRadius: avatarSize / 2,
        padding: 2,
        margin: 5,
        resizeMode: 'contain',
    },
    closeAvatarModalButton: {
        position: 'absolute',
        right: 10,
        top: 2,
        color: '#fff',
        fontSize: 22,
    },
    closeAvatarModalText: {
        color: '#fff',
        fontSize: 22,
        fontWeight: 'bold',
        padding: 5,
    },
    scoreRow: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    playerCardScoresContainer: {
        marginTop: 4,
        marginBottom: 4,
        borderColor: 'black',
        borderRadius: 3,
        padding: 3,
        backgroundColor: '#00000027',
        height: 60,
        width: '98%',
    },
    evenRow: {
        backgroundColor: '#ffffff00', // tai läpinäkyvä
    },

    oddRow: {
        backgroundColor: '#00000010', // kevyt tumma korostus, voit säätää
    },
    playerCardScoresTitle: {
        marginTop: 10,
        fontSize: 14,
        marginBottom: 0,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    playerCardScoreItem: {
        fontSize: 10,
        fontWeight: 'bold',
        color: '#000',
        width: '60%',
        marginLeft: 5,
        marginBottom: 2,

    },
    playerCardScoreDate: {
        fontSize: 10,
        fontWeight: 'bold',
        color: '#000000',
        textAlign: 'right',
        paddingTop: 2,
        marginRight: 5,
    },
    playerCardTrophyCase: {
        width: '98%',
        marginTop: 0,
        alignItems: 'center',
    },
    playerCardTrophyCaseTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        marginTop: 0,
        marginBottom: 2,
    },
    playerCardMonthsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        width: '100%',
    },
    playerCardMonth: {
        width: '23%',
        aspectRatio: 0.8,
        minHeight: 70,
        marginHorizontal: '1%',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 5,
        backgroundColor: '#fffcfc',
        borderRadius: 5,
        position: 'relative',
        flexDirection: 'column',
        borderColor: '#000',
        borderWidth: 1,
        opacity: 0.75,
    },
    playerCardOngoingMonth: {
        borderColor: 'green',
        borderWidth: 2,
        shadowColor: 'green',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        elevation: 12,
    },

    playerCardMonthText: {
        fontSize: 11,
        fontWeight: 'bold',
        textAlign: 'center',
        color: '#000',
        position: 'absolute',
        top: 0,
        marginBottom: 10,
        zIndex: 2,
        backgroundColor: '#ffffff8e',
        width: 56,
        borderTopLeftRadius: 3,
        borderTopRightRadius: 3,
    },
    emptySlotText: {
        fontSize: 12,
        color: 'black',
        textAlign: 'center',
    },
    playerCardCloseButton: {
        position: 'absolute',
        right: 10,
        top: 0,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        margin: 10,
        zIndex: 3,
    },
    playerCardCloseText: {
        color: 'black',
        fontSize: 22,
        fontWeight: 'bold',
        zIndex: 10,
        padding: 5,
    },
    nameAndLinkContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    linkIconContainer: {
        marginLeft: -15,
        marginRight: 5,
        padding: 5,
        borderRadius: 40,
        borderColor: '#4c4949',
        borderWidth: 1,
        backgroundColor: '#000000ba',
        alignSelf: 'center', // pysyy rivillä oikein
    },
    playerStatsContainer: {
        marginTop: 3,
        alignItems: 'left',
        marginLeft: 5,
        borderRadius: 2,
        padding: 2,
    },
    playerStat: {
        fontSize: 10,
        fontWeight: 'bold',
        color: '#000000',
        textAlign: 'center',
    },
    progressBar: {
        width: '85%',
        height: 15,
        marginLeft: 5,
        marginRight: 5,
        backgroundColor: '#FFFFFF',
        borderRadius: 2,
        marginVertical: 2,
        position: 'relative',
        borderWidth: 0.5,
        borderBottomWidth: 0,
        marginBottom: -3,
        alignSelf: 'center',
    },
    progressFill: {
        height: '100%',
        backgroundColor: '#24c92f',
        borderRadius: 2,
    },
    progressPercentageText: {
        position: 'absolute',
        width: '100%',
        textAlign: 'center',
        color: '#000000',
        fontWeight: 'bold',
        fontSize: 10,
        padding: 1,
    },
    playerCardHeader: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingTop: 5,
        marginBottom: 5,
        zIndex: 10,
    },

    playerCardNameText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#000',
    },

    playerCardInfoWrapper: {
        width: '100%',
        paddingHorizontal: 5,
        marginBottom: 10,
    },

    playerCardTopScoresWrapper: {
        width: '100%',
        paddingHorizontal: 5,
        marginTop: 0,
        marginBottom: 0,
    },
    playerCardHeaderCentered: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        position: 'relative',
        marginTop: 5,
    },

    playerCardNameTextCentered: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#000',
        textAlign: 'center',
    },

    playerCardCloseButton: {
        position: 'absolute',
        right: 10,
        top: -5,
        backgroundColor: 'transparent',
        zIndex: 2,
    },

    playerCardCloseText: {
        fontSize: 22,
        fontWeight: 'bold',
        color: 'black',
        padding: 5,
    },

});