import { StyleSheet } from 'react-native';
import { Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');
const isFoldScreen = width < 800;
const avatarSize = isFoldScreen ? 75 : 80;


export default styles = StyleSheet.create({

    // PlayerCard Styles
    playerCardContainer: {
        marginTop: 10,
        marginBottom: 10,
        alignItems: 'center',
    },
    playerInfoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        height: '18%',
        marginBottom: 5,
    },
    playerNameContainer: {
        marginLeft: 5,
    },
    playerCardName: {
        marginTop: 30,
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 5,
    },
    playerCardModalBackground: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        position: 'absolute',
        width: '100%',
        height: '100%',
    },
    playerCardModalContainer: {
        width: '80%',
        maxWidth: 350,
        marginTop: '5%',
        padding: 10,
        borderRadius: 10,
        alignItems: 'center',
        position: 'relative',
        overflow: 'hidden',
    },
    avatarModalBackgroundImage: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: '108%',
        height: '105%',
        borderRadius: 10,
        opacity: 0.95,
        resizeMode: 'cover',
    },
    trophyContainer: {
        position: 'relative',
        justifyContent: 'center',
        alignItems: 'center',
        height: "100%",
        width: "100%",
    },
    playerCardTrophyImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    trophyText: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        textAlign: 'center',
        color: '#ffffffff',
        fontSize: 9,
        fontWeight: 'bold',
    },
    // Avatar Styles
    avatarContainer: {
        width: 80,
        height: 80,
        borderRadius: 40,
        overflow: 'hidden',
        marginBottom: 0,
        borderWidth: 1,
        padding: 1,
        borderColor: '#00000063',
        marginRight: 5,
        marginLeft: 5,
        marginTop: 10,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#000000',
    },
    avatarModalBackground: {
        flex: 1,
        marginTop: '15%',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    avatarModalContainer: {
        width: '80%',
        height: '90%',
        backgroundColor: '#141414',
        borderRadius: 10,
        padding: 10,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#fff',
    },
    avatarSelectionWrapper: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-around',
        width: '100%',
    },
    avatar: {
        width: "100%",
        height: "100%",
        borderRadius: 50,
        margin: 5,
        resizeMode: 'cover',
    },
    editAvatarButton: {
        position: 'absolute',
        bottom: 0,
        left: "65%",
        borderWidth: 1,
        backgroundColor: '#ff000096',
        borderRadius: 20,
        padding: 5,
    },
    avatarSelectText: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 20,
        textAlign: 'center',
        color: '#fff',
    },
    avatarModalImageContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
        marginBottom: 50,
        borderColor: '#fff',
        borderWidth: 2,
        flexWrap: 'wrap',
    },
    avatarModalImage: {
        width: avatarSize,
        height: avatarSize,
        borderRadius: avatarSize / 2,
        padding: 2,
        margin: 5,
        resizeMode: 'contain',
    },
    closeAvatarModalButton: {
        position: 'absolute',
        right: 10,
        top: 2,
        color: '#fff',
        fontSize: 22,
    },
    closeAvatarModalText: {
        color: '#fff',
        fontSize: 22,
        fontWeight: 'bold',
        padding: 5,
    },
    scoreRow: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    playerCardScoresContainer: {
        marginTop: 5,
        marginBottom: 0,
    },
    playerCardScoresTitle: {
        marginTop: 0,
        fontSize: 18,
        marginBottom: 10,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    playerCardScoreItem: {
        marginTop: 0,
        fontSize: 14,
        fontWeight: 'bold',
        color: '#000',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        width: '100%',
        marginLeft: 15,
    },
    playerCardScoreDate: {
        fontSize: 11,
        fontWeight: 'bold',
        color: '#000000',
        textAlign: 'right',
        flex: 1,
        paddingTop: 2,
        marginRight: 15,
    },
    playerCardTrophyCase: {
        width: '100%',
        marginTop: -20,
        alignItems: 'center',
    },
    playerCardTrophyCaseTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 10,
    },
    playerCardMonthsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        width: '90%',
    },
    playerCardMonth: {
        width: '24%',
        height: 80,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 5,
        backgroundColor: '#f3f3f3',
        borderRadius: 5,
        position: 'relative',
        flexDirection: 'column',
        borderColor: '#000',
        borderWidth: 1,
        opacity: 0.75,
    },
    playerCardOngoingMonth: {
        borderColor: 'green',
        borderWidth: 4,
    },
    playerCardMonthText: {
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
        color: '#000000',
        top: -4,
        marginBottom: 10,
        position: 'absolute',
        zIndex: 2,
    },
    emptySlotText: {
        fontSize: 14,
        paddingTop: 10,
        color: 'black',
        textAlign: 'center',
    },
    playerCardCloseButton: {
        position: 'absolute',
        right: 21,
        top: 10,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        margin: 10,
        zIndex: 3,
    },
    playerCardCloseText: {
        color: 'black',
        fontSize: 22,
        fontWeight: 'bold',
        zIndex: 10,
        padding: 5,
    },
    linkIconContainer: {
        position: 'absolute',
        top: 5,
        left: 0,
        padding: 5,
        borderRadius: 40,
        borderColor: '#4c4949',
        borderWidth: 1,
        backgroundColor: '#000000ba',
    },
    playerStatsContainer: {
        marginTop: 0,
        alignItems: 'left',
        marginLeft: 5,
    },
    playerStat: {
        fontSize: 11,
        fontWeight: 'bold',
        color: '#000000',
    },

});