import { StyleSheet } from 'react-native';
import Constants from 'expo-constants';

export default styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#85715d',
    },
    homeContainer: {
        flex: 1,
        backgroundColor: '#85715d',
        justifyContent: 'center',
        alignItems: 'center',
        color: 'white',
    },
    header: {
        marginTop: Constants.statusBarHeight + 5,
        backgroundColor: 'darkorange',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    footer: {
        backgroundColor: 'darkorange',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    input: {
        padding: 8,
        margin: 10,
        width: 200,
        justifyContent: 'center',
        textAlign: 'center',
        fontFamily: 'AntonRegular',
    },
    inputIndexShown: {
        fontSize: 16,
        fontFamily: 'AntonRegular',
        color: '#4a4336',
        textAlign: 'center',
    },
    item: {
        flex: 1,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 3,
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    firstRowItem: {
        flex: 1,
        height: 25,
        alignItems: 'center',
        justifyContent: 'center',
    },
    text: {
        color: '#ffffff',
        fontWeight: 'bold',
    },
    playerText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 18,
        paddingTop: 5,
        textAlign: 'center',
    },
    firstRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 5,
    },
    lastRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 5,
    },
    diceContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    homeButton: {
        margin: 15,
        flexDirection: 'row',
        padding: 5,
        backgroundColor: '#ee8d1ef5',
        width: 200,
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    homeButtonPressed: {
        margin: 15,
        flexDirection: 'row',
        padding: 5,
        backgroundColor: 'orange',
        width: 200,
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 0,
        shadowRadius: 0,
        elevation: 0,
    },
    nameChangeBtn: {
        margin: 15,
        flexDirection: 'row',
        padding: 5,
        backgroundColor: 'orange',
        width: '40%',
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    button: {
        margin: 5,
        marginTop: 15,
        flexDirection: 'row',
        paddingLeft: 10,
        paddingRight: 10,
        backgroundColor: '#ee8d1ef5',
        width: '39%',
        height: 50,
        borderRadius: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    buttonPressed: {
        margin: 5,
        marginTop: 15,
        flexDirection: 'row',
        paddingLeft: 10,
        paddingRight: 10,
        backgroundColor: 'orange',
        width: '39%',
        height: 50,
        borderRadius: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 0.0,
        shadowRadius: 0,
        elevation: 0,
    },

    buttonText: {
        color: '#2B2B52',
        fontSize: 20,
        textAlign: 'center',
        fontFamily: 'AntonRegular',
    },
    nbrThrowsText: {
        fontSize: 16,
        fontFamily: 'AntonRegular',
        width: 35,
        height: 35,
        borderRadius: 100,
        color: 'white',
        borderWidth: 2,
        textAlign: 'center',
        alignContent: 'center',
        backgroundColor: 'red',
    },
    lastItem: {
        flex: 6,
    },
    icon: {
        justifyContent: 'center',
        alignItems: 'center',
        color: 'white',
    },
    gridTxt: {
        color: 'grey',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
        padding: 5,
        marginTop: 5,
        borderColor: 'white',
        borderRadius: 4,
        backgroundColor: 'white',
    },
    selectScore: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        color: 'grey',
        width: 80,
        marginRight: 15,
        marginTop: 5,
        fontSize: 20,
        textAlign: 'center',
        borderWidth: 1,
        borderColor: 'white',
        borderRadius: 4,
        backgroundColor: '#84786c',
        opacity: 0.3,
    },
    selectScorePressed: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        color: 'black',
        width: 80,
        marginRight: 15,
        marginTop: 5,
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        borderWidth: 2,
        borderColor: 'red',
        borderRadius: 4,
        backgroundColor: '#cf6d52b8',
    },
    lockedField: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        color: 'black',
        width: 80,
        marginRight: 15,
        marginTop: 5,
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        borderWidth: 3,
        borderColor: 'green',
        borderRadius: 4,
        backgroundColor: '#3ea645b8',
    },
    sectionContainer: {
        width: 70,
        height: 70,
        marginTop: 40,
        marginLeft: 10,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        borderRadius: 100,
        backgroundColor: 'orange',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    sectionBonusTxt: {
        fontSize: 12,
        textAlign: 'center',
        fontFamily: 'AntonRegular',
    },
    gameboard: {
        flex: 1,
        marginTop: 80,
        alignItems: 'center',
        justifyContent: 'center',
    },
    diceBorder: {
        width: '80%',
        height: 50,
        borderWidth: 1,
        borderColor: 'white',
        borderRadius: 4,
        alignItems: 'center',
        backgroundColor: '#594b4b',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        marginTop: -100,
    },
    row: {
        marginTop: 20,
        padding: 10,
    },
    flex: {
        flexDirection: 'row',
    },
    author: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 10,
        textAlign: 'center',
        margin: 10,
    },
    title: {
        color: '#fff',
        fontSize: 24,
        textAlign: 'center',
        margin: 5,
        fontFamily: 'AntonRegular',
    },
    rulesContainer: {
        height: 2000,
        flexGrow: 1,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
    },
    rulesText: {
        fontSize: 16,
        color: '#ffffff',
        textAlign: 'center',
        margin: 5,
        fontFamily: 'AntonRegular',
    },
    rulesCombination: {
        marginLeft: 20,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
        marginTop: 15,
    },
    rulesCombinationTxt: {
        flex: 1,
        fontSize: 12,
        color: '#ffffff',
        textAlign: 'center',
        justifyContent: 'center',
        marginBottom: 10,
        marginLeft: 10,
        marginRight: 10,
        fontFamily: 'AntonRegular',
    },
    lockedTextColor: {
        color: 'black',
    },

});
