import { StyleSheet } from 'react-native';
import Constants from 'expo-constants';

export default styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'stretch',
        backgroundColor: '#85715d',

    },
    homeContainer: {
        flex: 1,
        backgroundColor: '#85715d',
        justifyContent: 'center',
        alignItems: 'center',
        color: 'white',
    },
    header: {
        marginTop: Constants.statusBarHeight + 5,
        backgroundColor: 'darkorange',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    footer: {
        backgroundColor: 'darkorange',
        flexDirection: 'row',
        paddingBottom: 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    input: {
        padding: 8,
        margin: 10,
        width: 200,
        justifyContent: 'center',
        textAlign: 'center',
    },
    item: {
        flex: 1,
        height: 50,
        /* borderWidth: 2, */
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    firstRowItem: {
        flex: 1,
        height: 30,
        alignItems: 'center',
        justifyContent: 'center',
    },
    text: {
        color: '#fff',
        fontWeight: 'bold',
    },
    playerText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 14,
        paddingTop: 5,
        textAlign: 'center',
    },
    firstRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    lastRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 5,
    },
    diceContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 5,
    },
    homeButton: {
        margin: 15,
        flexDirection: 'row',
        padding: 5,
        backgroundColor: 'orange',
        width: '20%',
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    button: {
        margin: 5,
        marginTop: 15,
        flexDirection: 'row',
        padding: 10,
        backgroundColor: 'orange',
        width: '39%',
        height: 50,
        borderRadius: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    buttonPressed: {
        margin: 5,
        marginTop: 15,
        flexDirection: 'row',
        padding: 10,
        backgroundColor: 'orange',
        width: '39%',
        height: 50,
        borderRadius: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 0.0,
        shadowRadius: 0,
        elevation: 0,
    },
    buttonText: {
        color: '#2B2B52',
        fontSize: 20,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    nbrThrowsText: {
        fontSize: 16,
        width: 30,
        height: 30,
        borderRadius: 100,
        fontWeight: 'bold',
        color: 'white',
        borderWidth: 2,
        textAlign: 'center',
        padding: 2,
        backgroundColor: 'red',
    },
    lastItem: {
        flex: 6,
    },
    icon: {
        justifyContent: 'center',
        alignItems: 'center',
        color: 'white',
    },
    gridTxt: {
        color: 'grey',
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        paddingLeft: 4,
        paddingRight: 4,
        paddingTop: 6,
        paddingBottom: 0,
        borderWidth: 2,
        borderColor: 'white',
        borderRadius: 4,
        backgroundColor: 'white',
    },
    selectScore: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        color: 'grey',
        width: 80,
        marginRight: 15,
        marginTop: 5,
        fontSize: 20,
        textAlign: 'center',
        borderWidth: 1,
        borderColor: 'white',
        borderRadius: 4,
        backgroundColor: '#eec093',
    },
    selectScorePressed: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: 'bold',
        color: 'grey',
        width: 80,
        marginRight: 15,
        marginTop: 5,
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        borderWidth: 1,
        borderColor: 'white',
        borderRadius: 4,
        backgroundColor: 'orange',
    },
    sectionContainer: {
        width: 70,
        height: 70,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        borderRadius: 100,
        backgroundColor: 'orange',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    sectionBonusTxt: {
        fontSize: 12,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    gameboard: {
        flex: 1,
        marginTop: 120,
        alignItems: 'center',
        justifyContent: 'center',
    },
    diceBorder: {
        width: '80%',
        height: 65,
        borderWidth: 1,
        borderColor: 'white',
        borderRadius: 4,
        alignItems: 'center',
        backgroundColor: '#594b4b',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        marginTop: -100,
    },
    row: {
        marginTop: 20,
        padding: 10,
    },
    flex: {
        flexDirection: 'row',
    },
    author: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 10,
        textAlign: 'center',
        margin: 10,
    },
    title: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 23,
        textAlign: 'center',
        margin: 10,
    },
    rulesContainer: {
        height: 1600,
        flexGrow: 1,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
    },
    rulesText: {
        fontSize: 16,
        color: '#ffffff',
        textAlign: 'center',
        margin: 5,
    },
    rulesCombination: {
        marginLeft: 20,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
        marginTop: 15,
    },
    rulesCombinationTxt: {
        flex: 1,
        color: '#ffffff',
        textAlign: 'center',
        justifyContent: 'center',
        marginBottom: 10,
    },
});
