import { StyleSheet } from 'react-native';
import Constants from 'expo-constants';

export default styles = StyleSheet.create({
    container: {
        flex: 1,
        alignSelf: 'stretch',
    },
    background: {
        flex: 1,
        justifyContent: 'flex-start',
        width: '100%',
    },
    safeAreaView: {
        flex: 1,
    },
    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
    },
    header: {
        marginTop: Constants.statusBarHeight + 0,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
        position: 'relative',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 100,
        backgroundColor: 'rgba(0, 0, 0, 0.959)',
    },
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
    },
    userContainer: {
        flex: 1,
        right: 10,
    },
    userName: {
        fontSize: 12,
        fontWeight: 'bold',
        color: 'black',
        marginRight: 2,
    },
    footer: {
        backgroundColor: 'rgba(0, 0, 0, 0.95)',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    input: {
        padding: 8,
        margin: 10,
        width: 200,
        justifyContent: 'center',
        textAlign: 'center',
        fontFamily: 'AntonRegular',
        color: '#ccc9c9',
    },
    inputIndexShown: {
        fontSize: 16,
        fontFamily: 'AntonRegular',
        color: '#4a4336',
        textAlign: 'center',
    },
    item: {
        flex: 1,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 3,
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 10,
    },
    firstRowItem: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10,
    },

    firstRowCategoryText: {
        fontFamily: 'AntonRegular',
        fontSize: 16,
        color: '#ccc9c9',
        marginVertical: 0,
    },
    firstRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 0,
        margin: 0,
        zIndex: 10,
    },
    lastRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 5,
    },
    playerText: {
        fontWeight: 'bold',
        fontSize: 18,
        paddingTop: 5,
        textAlign: 'center',
    },
    diceContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    homeButton: {
        margin: 15,
        flexDirection: 'row',
        padding: 5,
        backgroundColor: '#ee8d1ef5',
        width: 200,
        borderWidth: 3,
        borderColor: 'orange',
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 10,
    },
    homeButtonPressed: {
        margin: 15,
        flexDirection: 'row',
        padding: 5,
        backgroundColor: 'orange',
        width: 200,
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 0,
        shadowRadius: 0,
        elevation: 0,
    },
    homeButtonContainer: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        width: '80%',
        marginTop: 20,
        marginBottom: 20,
    },
    rowButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginBottom: 10,
    },
    fullWidthButton: {
        marginTop: 5,
        flexDirection: 'row',
        paddingLeft: 10,
        paddingRight: 10,
        backgroundColor: '#ee8d1ef5',
        borderWidth: 3,
        borderColor: 'orange',
        width: '96%',
        height: 50,
        borderRadius: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 10,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    button: {
        margin: 5,
        marginTop: 15,
        flexDirection: 'row',
        paddingLeft: 10,
        paddingRight: 10,
        backgroundColor: '#ee8d1ef5',
        borderWidth: 3,
        borderColor: 'orange',
        width: '39%',
        height: 50,
        borderRadius: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 10,
    },
    buttonPressed: {
        margin: 5,
        marginTop: 15,
        flexDirection: 'row',
        paddingLeft: 10,
        paddingRight: 10,
        backgroundColor: 'orange',
        width: '39%',
        height: 50,
        borderRadius: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 0.0,
        shadowRadius: 0,
        elevation: 0,
    },
    userButton: {
        margin: 5,
        flexDirection: 'row',
        paddingLeft: 10,
        paddingRight: 10,
        backgroundColor: '#ee8d1ef5',
        borderWidth: 3,
        borderColor: 'black',
        width: '40%',
        height: '90%',
        borderRadius: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 10,
    },
    userButtonPressed: {
        margin: 5,
        flexDirection: 'row',
        paddingLeft: 10,
        paddingRight: 10,
        backgroundColor: 'orange',
        width: '40%',
        height: '90%',
        borderRadius: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 0.0,
        shadowRadius: 0,
        elevation: 0,
    },
    buttonText: {
        color: 'black',
        fontSize: 18,
        textAlign: 'center',
        fontFamily: 'AntonRegular',
    },
    nbrThrowsText: {
        fontSize: 17,
        fontFamily: 'AntonRegular',
        width: 35,
        height: 35,
        marginLeft: 10,
        borderRadius: 100,
        borderWidth: 2,
        textAlign: 'center',
        alignContent: 'center',
        justifyContent: 'center',
        backgroundColor: 'red',
    },
    lastItem: {
        flex: 6,
    },
    loadingContainer: {
        marginTop: 30,
    },
    icon: {
        justifyContent: 'center',
        alignItems: 'center',
        color: 'white',
    },
    gridTxt: {
        color: '#2c2418',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
        padding: 5,
        marginTop: 5,
        borderColor: '#ccc9c9',
        borderRadius: 4,
        backgroundColor: '#ccc9c9',
    },
    selectScore: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        color: 'grey',
        width: 80,
        marginRight: 15,
        marginTop: 5,
        fontSize: 20,
        textAlign: 'center',
        borderWidth: 1,
        borderColor: 'white',
        borderRadius: 4,
        backgroundColor: '#776c62',
    },
    selectScorePressed: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        color: 'black',
        width: 80,
        marginRight: 15,
        marginTop: 5,
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        borderWidth: 2,
        borderColor: 'red',
        borderRadius: 4,
        backgroundColor: '#cf6d52b8',
    },
    scoreText: {
        color: 'white',
        fontFamily: 'AntonRegular',
        paddingRight: 10,
    },
    lockedField: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        color: 'black',
        width: 80,
        marginRight: 15,
        marginTop: 5,
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        borderWidth: 3,
        borderColor: 'green',
        borderRadius: 4,
        backgroundColor: '#3ea645b8',
    },
    sectionContainer: {
        width: 70,
        height: 70,
        marginTop: 45,
        marginLeft: 10,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        borderRadius: 100,
        borderWidth: 1,
        borderColor: 'white',
        backgroundColor: '#84786c',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 10,
    },
    sectionContainerAchieved: {
        width: 72,
        height: 72,
        marginTop: 40,
        marginLeft: 10,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        borderRadius: 100,
        borderWidth: 3,
        borderColor: 'green',
        backgroundColor: '#3ea645b8',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    sectionBonusTxt: {
        fontSize: 12,
        textAlign: 'center',
        color: '#2c2418',
        fontFamily: 'AntonRegular',
    },
    gameboard: {
        flex: 1,
        marginTop: 90,
        alignItems: 'center',
        justifyContent: 'center',
    },
    filterLayer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        zIndex: 999,
        justifyContent: 'center',
        alignItems: 'center',
        display: 'flex',
    },
    centeredText: {
        color: 'white',
        fontSize: 32,
        fontWeight: 'bold',
        textAlign: 'center',
        textShadowColor: '#ff0000',
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 10,
        zIndex: 1000,
    },
    diceBorder: {
        width: '80%',
        height: 60,
        borderWidth: 2,
        borderColor: '#ccc9c9',
        borderRadius: 4,
        alignItems: 'center',
        backgroundColor: 'black',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 10,
        marginTop: -100,
    },
    row: {
        marginTop: 20,
        padding: 10,
    },
    flex: {
        flexDirection: 'row',
    },
    author: {
        fontWeight: 'bold',
        fontSize: 10,
        textAlign: 'center',
        margin: 5,
        color: '#ccc9c9',
    },
    headerTitle: {
        fontSize: 24,
        textAlign: 'center',
        margin: 10,
        fontFamily: 'AntonRegular',
        color: '#ccc9c9',
    },
    rulesContainer: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
    },
    rulesContent: {
        justifyContent: 'center',
        alignItems: 'center',
        padding: 15,
        backgroundColor: '#282828',
        borderRadius: 10,
    },
    rulesText: {
        fontSize: 16,
        top: -60,
        width: '90%',
        color: '#ccc9c9',
        textAlign: 'center',
        fontFamily: 'AntonRegular',
        alignSelf: 'center',
    },
    rulesCombination: {
        marginLeft: 20,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
        marginTop: 15,
    },
    rulesCombinationTxt: {
        flex: 1,
        fontSize: 12,
        color: '#ccc9c9',
        textAlign: 'center',
        justifyContent: 'center',
        marginBottom: 10,
        marginLeft: 10,
        marginRight: 10,
        fontFamily: 'AntonRegular',
    },
    smallText: {
    fontSize: 10,
    marginLeft: 10,
    color: 'white',
    width: 60,
    },
    lockedTextColor: {
        color: 'black',
    },
    scoreboardContainer: {
        alignSelf: 'center',
        borderRadius: 5,
        backgroundColor: '#575555',
        width: '95%',
        textAlign: 'center',
        justifyContent: 'center',
        borderColor: '#393838',
        opacity: 0.90,
        borderWidth: 2,
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 5,
        },
        shadowOpacity: 0.5,
        shadowRadius: 3.84,
        elevation: 10,
    },
    cell: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    scoreboardHeader: {
        fontSize: 14,
        textAlign: 'center',
        fontFamily: 'AntonRegular',
        color: 'black',
        paddingVertical: 5,
    },

    scoreboardText: {
        fontSize: 12,
        textAlign: 'center',
        fontFamily: 'Roboto',
        fontWeight: '800',
        color: '#050404',
        paddingVertical: 5,
    },
    //Modal
    modalCenteredView: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        maxHeight: '60%',
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 1,
    },
    modalView: {
        margin: 20,
        backgroundColor: '#ffffff',
        borderRadius: 5,
        padding: 30,
        alignItems: 'center',
        opacity: 0.95,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 8,
    },
    modalText: {
        marginBottom: 10,
        textAlign: 'center',
        fontSize: 16,
        color: 'black',
        fontWeight: '500',
    },
    modalButton: {
        borderRadius: 5,
        paddingVertical: 8,
        paddingHorizontal: 15,
        elevation: 3,
        backgroundColor: '#ffa500',
    },
    modalButtonText: {
        color: 'black',
        fontWeight: '600',
        textAlign: 'center',
        fontSize: 16,
    },
    modalCloseButton: {
        position: 'absolute',
        right: 20,
        top: 10,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
    },
    modalCloseButtonText: {
        color: 'black',
        fontSize: 22,
        fontWeight: 'bold',
    },
    modalItemRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 15,
        paddingVertical: 5,
        width: '100%',
    },
    modalSubText: {
        fontSize: 14,
        color: 'gray',
        textAlign: 'right',
        marginLeft: 10,
    },
    modalDivider: {
        height: 1,
        backgroundColor: '#d3d3d3',
        marginVertical: 5,
        width: '100%',
    },
    modalItemContainer: {
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 15,
    },
    modalSubText: {
        fontSize: 14,
        color: '#a9a9a9',
        textAlign: 'center',
        fontStyle: 'italic',
    },
    // AboutMe
    aboutContainer: {
        flexGrow: 1,
        backgroundColor: 'rgba(0, 0, 0, 0)',
        padding: 20,
    },
    headerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    profileImage: {
        width: 100,
        height: 100,
        borderRadius: 50,
        borderWidth: 2,
        borderColor: '#e3dddd',
        marginLeft: 20,
    },
    aboutTitle: {
        fontSize: 24,
        paddingLeft: 20,
        color: '#e3dddd',
        fontFamily: 'AntonRegular',
    },
    aboutText: {
        fontSize: 16,
        padding: 15,
        color: '#e3dddd',
        textAlign: 'center',
        fontFamily: 'AntonRegular',
    },
    aboutFeatureText: {
        fontSize: 16,
        marginLeft: 15,
        marginRight: 15,
        marginBottom: 20,
        color: '#e3dddd',
        fontFamily: 'AntonRegular',
        textAlign: 'left',
    },
    timer: {
        fontSize: 18,
        fontWeight: 'bold',
        color: 'black',
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: [{ translateX: -50 }, { translateY: -50 }],
    },
    // StartGame button
    startModalButton: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(1, 1, 1, 1)',
        maxHeight: '100%',
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 999,

    },
    // StartGame button text
    startModalButtonText: {
        color: 'white',
        textAlign: 'center',
        fontSize: 20,
        fontWeight: 'bold',
        textShadowColor: '#ff0000',
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 10,
        zIndex: 999,
    },
    // Info button
    infoButton: {
        position: 'absolute',
        top: 10,
        right: 10,
        borderRadius: 40,
        padding: 5,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#fff',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 5,
    },
    tabContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 20,
        marginBottom: 10,
    },
    tabText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'white',
        padding: 10,
    },
    activeTab: {
        borderBottomWidth: 2,
        borderBottomColor: 'gold',
        padding: 10,
    },
    inactiveTab: {
        padding: 10,
    },
    scoresHeaderContainer: {
        alignItems: 'center',
        marginTop: 20,
    },
    scoresHeaderText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: 'white',
    },

});
